spring:
  application:
    name: rating-service
  datasource:
    url: ${DATABASE_URL}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 900000
  profiles:
    active: ${ENVIRONMENT:development}

grpc:
  server:
    port: ${PORT:6565}

management:
  metrics:
    export:
      simple:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.esclient: ${LOG_LEVEL:DEBUG}
    org.springframework: WARN
    org.hibernate: WARN
    io.grpc: INFO
    org.springframework.boot.autoconfigure: WARN
  file:
    name: logs/rating-service.log
    path: logs
  pattern:
    console: ""  # Disable default pattern (we use JSON)
    file: ""     # Disable default pattern (we use JSON)
