spring:
  application:
    name: rating-service

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: false

grpc:
  server:
    port: ${SERVER_PORT:8080}

management:
  metrics:
    export:
      simple:
        enabled: true
