package com.esclient.ratingservice.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "ratings")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Rating {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(name = "user_id")
    private String userId;
    
    @Column(name = "item_id")
    private String itemId;
    
    @Column(name = "rating")
    private Double rating;
    
    @Column(name = "comment")
    private String comment;
    
    // The equals method should use getId() which will be generated by Lombok
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Rating rating = (Rating) o;
        return getId() != null && getId().equals(rating.getId());
    }
    
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}