// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating.proto

package rating;

public final class Rating {
  private Rating() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RateModRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rating.RateModRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 mod_id = 1;</code>
     * @return The modId.
     */
    long getModId();

    /**
     * <code>int64 author_id = 2;</code>
     * @return The authorId.
     */
    long getAuthorId();

    /**
     * <code>int32 rate = 3;</code>
     * @return The rate.
     */
    int getRate();
  }
  /**
   * Protobuf type {@code rating.RateModRequest}
   */
  public static final class RateModRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rating.RateModRequest)
      RateModRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RateModRequest.newBuilder() to construct.
    private RateModRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RateModRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RateModRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rating.Rating.internal_static_rating_RateModRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rating.Rating.internal_static_rating_RateModRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rating.Rating.RateModRequest.class, rating.Rating.RateModRequest.Builder.class);
    }

    public static final int MOD_ID_FIELD_NUMBER = 1;
    private long modId_ = 0L;
    /**
     * <code>int64 mod_id = 1;</code>
     * @return The modId.
     */
    @java.lang.Override
    public long getModId() {
      return modId_;
    }

    public static final int AUTHOR_ID_FIELD_NUMBER = 2;
    private long authorId_ = 0L;
    /**
     * <code>int64 author_id = 2;</code>
     * @return The authorId.
     */
    @java.lang.Override
    public long getAuthorId() {
      return authorId_;
    }

    public static final int RATE_FIELD_NUMBER = 3;
    private int rate_ = 0;
    /**
     * <code>int32 rate = 3;</code>
     * @return The rate.
     */
    @java.lang.Override
    public int getRate() {
      return rate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (modId_ != 0L) {
        output.writeInt64(1, modId_);
      }
      if (authorId_ != 0L) {
        output.writeInt64(2, authorId_);
      }
      if (rate_ != 0) {
        output.writeInt32(3, rate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (modId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, modId_);
      }
      if (authorId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, authorId_);
      }
      if (rate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rating.Rating.RateModRequest)) {
        return super.equals(obj);
      }
      rating.Rating.RateModRequest other = (rating.Rating.RateModRequest) obj;

      if (getModId()
          != other.getModId()) return false;
      if (getAuthorId()
          != other.getAuthorId()) return false;
      if (getRate()
          != other.getRate()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MOD_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getModId());
      hash = (37 * hash) + AUTHOR_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAuthorId());
      hash = (37 * hash) + RATE_FIELD_NUMBER;
      hash = (53 * hash) + getRate();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rating.Rating.RateModRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rating.Rating.RateModRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rating.Rating.RateModRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rating.Rating.RateModRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rating.Rating.RateModRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rating.Rating.RateModRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rating.Rating.RateModRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rating.Rating.RateModRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rating.Rating.RateModRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rating.Rating.RateModRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rating.Rating.RateModRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rating.Rating.RateModRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rating.Rating.RateModRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rating.RateModRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rating.RateModRequest)
        rating.Rating.RateModRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rating.Rating.internal_static_rating_RateModRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rating.Rating.internal_static_rating_RateModRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rating.Rating.RateModRequest.class, rating.Rating.RateModRequest.Builder.class);
      }

      // Construct using rating.Rating.RateModRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        modId_ = 0L;
        authorId_ = 0L;
        rate_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rating.Rating.internal_static_rating_RateModRequest_descriptor;
      }

      @java.lang.Override
      public rating.Rating.RateModRequest getDefaultInstanceForType() {
        return rating.Rating.RateModRequest.getDefaultInstance();
      }

      @java.lang.Override
      public rating.Rating.RateModRequest build() {
        rating.Rating.RateModRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rating.Rating.RateModRequest buildPartial() {
        rating.Rating.RateModRequest result = new rating.Rating.RateModRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(rating.Rating.RateModRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.modId_ = modId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.authorId_ = authorId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.rate_ = rate_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rating.Rating.RateModRequest) {
          return mergeFrom((rating.Rating.RateModRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rating.Rating.RateModRequest other) {
        if (other == rating.Rating.RateModRequest.getDefaultInstance()) return this;
        if (other.getModId() != 0L) {
          setModId(other.getModId());
        }
        if (other.getAuthorId() != 0L) {
          setAuthorId(other.getAuthorId());
        }
        if (other.getRate() != 0) {
          setRate(other.getRate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                modId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                authorId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                rate_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long modId_ ;
      /**
       * <code>int64 mod_id = 1;</code>
       * @return The modId.
       */
      @java.lang.Override
      public long getModId() {
        return modId_;
      }
      /**
       * <code>int64 mod_id = 1;</code>
       * @param value The modId to set.
       * @return This builder for chaining.
       */
      public Builder setModId(long value) {
        
        modId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 mod_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearModId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        modId_ = 0L;
        onChanged();
        return this;
      }

      private long authorId_ ;
      /**
       * <code>int64 author_id = 2;</code>
       * @return The authorId.
       */
      @java.lang.Override
      public long getAuthorId() {
        return authorId_;
      }
      /**
       * <code>int64 author_id = 2;</code>
       * @param value The authorId to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorId(long value) {
        
        authorId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 author_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        authorId_ = 0L;
        onChanged();
        return this;
      }

      private int rate_ ;
      /**
       * <code>int32 rate = 3;</code>
       * @return The rate.
       */
      @java.lang.Override
      public int getRate() {
        return rate_;
      }
      /**
       * <code>int32 rate = 3;</code>
       * @param value The rate to set.
       * @return This builder for chaining.
       */
      public Builder setRate(int value) {
        
        rate_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 rate = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rate_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rating.RateModRequest)
    }

    // @@protoc_insertion_point(class_scope:rating.RateModRequest)
    private static final rating.Rating.RateModRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rating.Rating.RateModRequest();
    }

    public static rating.Rating.RateModRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RateModRequest>
        PARSER = new com.google.protobuf.AbstractParser<RateModRequest>() {
      @java.lang.Override
      public RateModRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RateModRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RateModRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rating.Rating.RateModRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RateModResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rating.RateModResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 rate_id = 1;</code>
     * @return The rateId.
     */
    long getRateId();
  }
  /**
   * Protobuf type {@code rating.RateModResponse}
   */
  public static final class RateModResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rating.RateModResponse)
      RateModResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RateModResponse.newBuilder() to construct.
    private RateModResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RateModResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RateModResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rating.Rating.internal_static_rating_RateModResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rating.Rating.internal_static_rating_RateModResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rating.Rating.RateModResponse.class, rating.Rating.RateModResponse.Builder.class);
    }

    public static final int RATE_ID_FIELD_NUMBER = 1;
    private long rateId_ = 0L;
    /**
     * <code>int64 rate_id = 1;</code>
     * @return The rateId.
     */
    @java.lang.Override
    public long getRateId() {
      return rateId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rateId_ != 0L) {
        output.writeInt64(1, rateId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rateId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rateId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rating.Rating.RateModResponse)) {
        return super.equals(obj);
      }
      rating.Rating.RateModResponse other = (rating.Rating.RateModResponse) obj;

      if (getRateId()
          != other.getRateId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RATE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRateId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rating.Rating.RateModResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rating.Rating.RateModResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rating.Rating.RateModResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rating.Rating.RateModResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rating.Rating.RateModResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rating.Rating.RateModResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rating.Rating.RateModResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rating.Rating.RateModResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rating.Rating.RateModResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rating.Rating.RateModResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rating.Rating.RateModResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rating.Rating.RateModResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rating.Rating.RateModResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rating.RateModResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rating.RateModResponse)
        rating.Rating.RateModResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rating.Rating.internal_static_rating_RateModResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rating.Rating.internal_static_rating_RateModResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rating.Rating.RateModResponse.class, rating.Rating.RateModResponse.Builder.class);
      }

      // Construct using rating.Rating.RateModResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        rateId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rating.Rating.internal_static_rating_RateModResponse_descriptor;
      }

      @java.lang.Override
      public rating.Rating.RateModResponse getDefaultInstanceForType() {
        return rating.Rating.RateModResponse.getDefaultInstance();
      }

      @java.lang.Override
      public rating.Rating.RateModResponse build() {
        rating.Rating.RateModResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rating.Rating.RateModResponse buildPartial() {
        rating.Rating.RateModResponse result = new rating.Rating.RateModResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(rating.Rating.RateModResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.rateId_ = rateId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rating.Rating.RateModResponse) {
          return mergeFrom((rating.Rating.RateModResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rating.Rating.RateModResponse other) {
        if (other == rating.Rating.RateModResponse.getDefaultInstance()) return this;
        if (other.getRateId() != 0L) {
          setRateId(other.getRateId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                rateId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long rateId_ ;
      /**
       * <code>int64 rate_id = 1;</code>
       * @return The rateId.
       */
      @java.lang.Override
      public long getRateId() {
        return rateId_;
      }
      /**
       * <code>int64 rate_id = 1;</code>
       * @param value The rateId to set.
       * @return This builder for chaining.
       */
      public Builder setRateId(long value) {
        
        rateId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rate_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRateId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rateId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rating.RateModResponse)
    }

    // @@protoc_insertion_point(class_scope:rating.RateModResponse)
    private static final rating.Rating.RateModResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rating.Rating.RateModResponse();
    }

    public static rating.Rating.RateModResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RateModResponse>
        PARSER = new com.google.protobuf.AbstractParser<RateModResponse>() {
      @java.lang.Override
      public RateModResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RateModResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RateModResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rating.Rating.RateModResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetRatesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rating.GetRatesRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 mod_id = 1;</code>
     * @return The modId.
     */
    long getModId();
  }
  /**
   * Protobuf type {@code rating.GetRatesRequest}
   */
  public static final class GetRatesRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rating.GetRatesRequest)
      GetRatesRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetRatesRequest.newBuilder() to construct.
    private GetRatesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetRatesRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetRatesRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rating.Rating.internal_static_rating_GetRatesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rating.Rating.internal_static_rating_GetRatesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rating.Rating.GetRatesRequest.class, rating.Rating.GetRatesRequest.Builder.class);
    }

    public static final int MOD_ID_FIELD_NUMBER = 1;
    private long modId_ = 0L;
    /**
     * <code>int64 mod_id = 1;</code>
     * @return The modId.
     */
    @java.lang.Override
    public long getModId() {
      return modId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (modId_ != 0L) {
        output.writeInt64(1, modId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (modId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, modId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rating.Rating.GetRatesRequest)) {
        return super.equals(obj);
      }
      rating.Rating.GetRatesRequest other = (rating.Rating.GetRatesRequest) obj;

      if (getModId()
          != other.getModId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MOD_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getModId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rating.Rating.GetRatesRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rating.Rating.GetRatesRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rating.Rating.GetRatesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rating.Rating.GetRatesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rating.Rating.GetRatesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rating.Rating.GetRatesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rating.Rating.GetRatesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rating.Rating.GetRatesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rating.Rating.GetRatesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rating.Rating.GetRatesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rating.Rating.GetRatesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rating.Rating.GetRatesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rating.Rating.GetRatesRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rating.GetRatesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rating.GetRatesRequest)
        rating.Rating.GetRatesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rating.Rating.internal_static_rating_GetRatesRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rating.Rating.internal_static_rating_GetRatesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rating.Rating.GetRatesRequest.class, rating.Rating.GetRatesRequest.Builder.class);
      }

      // Construct using rating.Rating.GetRatesRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        modId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rating.Rating.internal_static_rating_GetRatesRequest_descriptor;
      }

      @java.lang.Override
      public rating.Rating.GetRatesRequest getDefaultInstanceForType() {
        return rating.Rating.GetRatesRequest.getDefaultInstance();
      }

      @java.lang.Override
      public rating.Rating.GetRatesRequest build() {
        rating.Rating.GetRatesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rating.Rating.GetRatesRequest buildPartial() {
        rating.Rating.GetRatesRequest result = new rating.Rating.GetRatesRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(rating.Rating.GetRatesRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.modId_ = modId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rating.Rating.GetRatesRequest) {
          return mergeFrom((rating.Rating.GetRatesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rating.Rating.GetRatesRequest other) {
        if (other == rating.Rating.GetRatesRequest.getDefaultInstance()) return this;
        if (other.getModId() != 0L) {
          setModId(other.getModId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                modId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long modId_ ;
      /**
       * <code>int64 mod_id = 1;</code>
       * @return The modId.
       */
      @java.lang.Override
      public long getModId() {
        return modId_;
      }
      /**
       * <code>int64 mod_id = 1;</code>
       * @param value The modId to set.
       * @return This builder for chaining.
       */
      public Builder setModId(long value) {
        
        modId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 mod_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearModId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        modId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rating.GetRatesRequest)
    }

    // @@protoc_insertion_point(class_scope:rating.GetRatesRequest)
    private static final rating.Rating.GetRatesRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rating.Rating.GetRatesRequest();
    }

    public static rating.Rating.GetRatesRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetRatesRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetRatesRequest>() {
      @java.lang.Override
      public GetRatesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetRatesRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetRatesRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rating.Rating.GetRatesRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetRatesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rating.GetRatesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 rates_total = 1;</code>
     * @return The ratesTotal.
     */
    long getRatesTotal();

    /**
     * <code>int64 likes = 2;</code>
     * @return The likes.
     */
    long getLikes();

    /**
     * <code>int64 dislikes = 3;</code>
     * @return The dislikes.
     */
    long getDislikes();
  }
  /**
   * Protobuf type {@code rating.GetRatesResponse}
   */
  public static final class GetRatesResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rating.GetRatesResponse)
      GetRatesResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetRatesResponse.newBuilder() to construct.
    private GetRatesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetRatesResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetRatesResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rating.Rating.internal_static_rating_GetRatesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rating.Rating.internal_static_rating_GetRatesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rating.Rating.GetRatesResponse.class, rating.Rating.GetRatesResponse.Builder.class);
    }

    public static final int RATES_TOTAL_FIELD_NUMBER = 1;
    private long ratesTotal_ = 0L;
    /**
     * <code>int64 rates_total = 1;</code>
     * @return The ratesTotal.
     */
    @java.lang.Override
    public long getRatesTotal() {
      return ratesTotal_;
    }

    public static final int LIKES_FIELD_NUMBER = 2;
    private long likes_ = 0L;
    /**
     * <code>int64 likes = 2;</code>
     * @return The likes.
     */
    @java.lang.Override
    public long getLikes() {
      return likes_;
    }

    public static final int DISLIKES_FIELD_NUMBER = 3;
    private long dislikes_ = 0L;
    /**
     * <code>int64 dislikes = 3;</code>
     * @return The dislikes.
     */
    @java.lang.Override
    public long getDislikes() {
      return dislikes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ratesTotal_ != 0L) {
        output.writeInt64(1, ratesTotal_);
      }
      if (likes_ != 0L) {
        output.writeInt64(2, likes_);
      }
      if (dislikes_ != 0L) {
        output.writeInt64(3, dislikes_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ratesTotal_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, ratesTotal_);
      }
      if (likes_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, likes_);
      }
      if (dislikes_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, dislikes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rating.Rating.GetRatesResponse)) {
        return super.equals(obj);
      }
      rating.Rating.GetRatesResponse other = (rating.Rating.GetRatesResponse) obj;

      if (getRatesTotal()
          != other.getRatesTotal()) return false;
      if (getLikes()
          != other.getLikes()) return false;
      if (getDislikes()
          != other.getDislikes()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RATES_TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRatesTotal());
      hash = (37 * hash) + LIKES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLikes());
      hash = (37 * hash) + DISLIKES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDislikes());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rating.Rating.GetRatesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rating.Rating.GetRatesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rating.Rating.GetRatesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rating.Rating.GetRatesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rating.Rating.GetRatesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rating.Rating.GetRatesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rating.Rating.GetRatesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rating.Rating.GetRatesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rating.Rating.GetRatesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rating.Rating.GetRatesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rating.Rating.GetRatesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rating.Rating.GetRatesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rating.Rating.GetRatesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rating.GetRatesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rating.GetRatesResponse)
        rating.Rating.GetRatesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rating.Rating.internal_static_rating_GetRatesResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rating.Rating.internal_static_rating_GetRatesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rating.Rating.GetRatesResponse.class, rating.Rating.GetRatesResponse.Builder.class);
      }

      // Construct using rating.Rating.GetRatesResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ratesTotal_ = 0L;
        likes_ = 0L;
        dislikes_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rating.Rating.internal_static_rating_GetRatesResponse_descriptor;
      }

      @java.lang.Override
      public rating.Rating.GetRatesResponse getDefaultInstanceForType() {
        return rating.Rating.GetRatesResponse.getDefaultInstance();
      }

      @java.lang.Override
      public rating.Rating.GetRatesResponse build() {
        rating.Rating.GetRatesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rating.Rating.GetRatesResponse buildPartial() {
        rating.Rating.GetRatesResponse result = new rating.Rating.GetRatesResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(rating.Rating.GetRatesResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ratesTotal_ = ratesTotal_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.likes_ = likes_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.dislikes_ = dislikes_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rating.Rating.GetRatesResponse) {
          return mergeFrom((rating.Rating.GetRatesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rating.Rating.GetRatesResponse other) {
        if (other == rating.Rating.GetRatesResponse.getDefaultInstance()) return this;
        if (other.getRatesTotal() != 0L) {
          setRatesTotal(other.getRatesTotal());
        }
        if (other.getLikes() != 0L) {
          setLikes(other.getLikes());
        }
        if (other.getDislikes() != 0L) {
          setDislikes(other.getDislikes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                ratesTotal_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                likes_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                dislikes_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long ratesTotal_ ;
      /**
       * <code>int64 rates_total = 1;</code>
       * @return The ratesTotal.
       */
      @java.lang.Override
      public long getRatesTotal() {
        return ratesTotal_;
      }
      /**
       * <code>int64 rates_total = 1;</code>
       * @param value The ratesTotal to set.
       * @return This builder for chaining.
       */
      public Builder setRatesTotal(long value) {
        
        ratesTotal_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rates_total = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRatesTotal() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ratesTotal_ = 0L;
        onChanged();
        return this;
      }

      private long likes_ ;
      /**
       * <code>int64 likes = 2;</code>
       * @return The likes.
       */
      @java.lang.Override
      public long getLikes() {
        return likes_;
      }
      /**
       * <code>int64 likes = 2;</code>
       * @param value The likes to set.
       * @return This builder for chaining.
       */
      public Builder setLikes(long value) {
        
        likes_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 likes = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLikes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        likes_ = 0L;
        onChanged();
        return this;
      }

      private long dislikes_ ;
      /**
       * <code>int64 dislikes = 3;</code>
       * @return The dislikes.
       */
      @java.lang.Override
      public long getDislikes() {
        return dislikes_;
      }
      /**
       * <code>int64 dislikes = 3;</code>
       * @param value The dislikes to set.
       * @return This builder for chaining.
       */
      public Builder setDislikes(long value) {
        
        dislikes_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 dislikes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDislikes() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dislikes_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rating.GetRatesResponse)
    }

    // @@protoc_insertion_point(class_scope:rating.GetRatesResponse)
    private static final rating.Rating.GetRatesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rating.Rating.GetRatesResponse();
    }

    public static rating.Rating.GetRatesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetRatesResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetRatesResponse>() {
      @java.lang.Override
      public GetRatesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetRatesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetRatesResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rating.Rating.GetRatesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_RateModRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rating_RateModRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_RateModResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rating_RateModResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_GetRatesRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rating_GetRatesRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_GetRatesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rating_GetRatesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014rating.proto\022\006rating\"A\n\016RateModRequest" +
      "\022\016\n\006mod_id\030\001 \001(\003\022\021\n\tauthor_id\030\002 \001(\003\022\014\n\004r" +
      "ate\030\003 \001(\005\"\"\n\017RateModResponse\022\017\n\007rate_id\030" +
      "\001 \001(\003\"!\n\017GetRatesRequest\022\016\n\006mod_id\030\001 \001(\003" +
      "\"H\n\020GetRatesResponse\022\023\n\013rates_total\030\001 \001(" +
      "\003\022\r\n\005likes\030\002 \001(\003\022\020\n\010dislikes\030\003 \001(\0032\212\001\n\rR" +
      "atingService\022:\n\007RateMod\022\026.rating.RateMod" +
      "Request\032\027.rating.RateModResponse\022=\n\010GetR" +
      "ates\022\027.rating.GetRatesRequest\032\030.rating.G" +
      "etRatesResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rating_RateModRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rating_RateModRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rating_RateModRequest_descriptor,
        new java.lang.String[] { "ModId", "AuthorId", "Rate", });
    internal_static_rating_RateModResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rating_RateModResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rating_RateModResponse_descriptor,
        new java.lang.String[] { "RateId", });
    internal_static_rating_GetRatesRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rating_GetRatesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rating_GetRatesRequest_descriptor,
        new java.lang.String[] { "ModId", });
    internal_static_rating_GetRatesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_rating_GetRatesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rating_GetRatesResponse_descriptor,
        new java.lang.String[] { "RatesTotal", "Likes", "Dislikes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
